version: "3"
services:
    ghost:
        image: ghost:1-alpine
        restart: always
        ports:
          - 127.0.0.1:8080:2368
        volumes:
          - ./blog/data/ghost:/var/lib/ghost/content
        environment:
          - url=https://blog.aaronlenoir.com
          - VIRTUAL_HOST=blog.aaronlenoir.com
          - LETSENCRYPT_HOST=blog.aaronlenoir.com
          - LETSENCRYPT_EMAIL=info@aaronlenoir.com

networks:
  default:
    external:
      name: nginx-proxy
