version: '2'

services:
  miniflux:
    image: miniflux/miniflux:latest
    expose:
      - 80
    volumes:
      - miniflux_data:/var/www/html/data
    environment:
      VIRTUAL_HOST: dinasaccarola.me
      LETSENCRYPT_HOST: dinasaccarola.me
      LETSENCRYPT_EMAIL: kevingracia07@gmail.com

volumes:
  miniflux_data:
        driver: local

networks:
    default:
        external:
            name: nginx-proxy
