version: '3.1'

services:
  joomla:
    image: joomla:3.9.5-php7.3-fpm-alpine
    restart: always
    environment:
      JOOMLA_DB_HOST=db
      JOOMLA_DB_USER=postgres
      JOOMLA_DB_PASSWORD=mysecretpassword
      JOOMLA_DB_NAME=db
      VIRTUAL_HOST: kevingo.codes
      LETSENCRYPT_HOST: kevingo.codes
      LETSENCRYPT_EMAIL: corre@dominio.com
    volumes:
      - ./joomla:/var/www/html
      - ./makedb.php:/makedb.php
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./db:/var/lib/postgresql/data
networks:
  default:
    external:
      name: nginx-proxy
